Fix stack reference subsetting
jcpsantiago/sentryR pull request #29
Opened 2023-08-11 04:49 UTC by egnor

- builds a stack tibble, _then_ removes "boring" functions, to make sure everything stays aligned
- adds `simplify = FALSE` to fix a buglet with very short stacks
- adds a test case for call stack conversion

Fixes https://github.com/EduSemensati/sentryR/issues/25

2024-01-02 12:59 UTC, jcpsantiago commented
Thanks @egnor!

2024-01-02 13:00 UTC, jcpsantiago requested changes
Looks good to me. Could you solve the conflicts? I'll merge it afterwards. Thanks again for your contribution!

2024-01-03 01:21 UTC, egnor commented
Unfortunately the company I was doing that work for has folded, and that repo is frozen.

But, just to land this change, I forked that repo into my own account and will open a new PR from there!

2024-01-03 01:21 UTC, closed without merging

2024-01-03 09:47 UTC, jcpsantiago commented
Oh sorry to hear that!